# Generated by Django 2.2.5 on 2021-11-13 06:51

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='题目文本')),
                ('label_img', models.CharField(max_length=256, verbose_name='题目标签图片')),
                ('updated_at', models.IntegerField(default=time.time)),
                ('created_at', models.IntegerField(default=time.time)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('parent_uuid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('updated_at', models.IntegerField(default=time.time)),
                ('created_at', models.IntegerField(default=time.time)),
            ],
        ),
    ]
