# Generated by Django 2.2.5 on 2021-11-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '数学题目', 'verbose_name_plural': '数学题目'},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': '知识点', 'verbose_name_plural': '知识点'},
        ),
        migrations.AlterField(
            model_name='content',
            name='label_img',
            field=models.CharField(max_length=625, verbose_name='题目标签图片'),
        ),
    ]
